### ISSUE TITLE
Should we support expression-based filtering of data when we source/sink it?

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/old-argo-dataflow#23]
```yaml
      sinks:
        - filter: 'toJson(message).type == "cat"'
          bus:
            subject: animals
```
